title: Hossein Tahmasbi
email: h.tahmasb@gmail.com
description: >-
  Personal site of Hossein Tahmasbi — software engineer, problem solver,
  and lifelong learner.
baseurl: ""
url: "https://htahmasbi.github.io"
gitlab_username: h.tahmasbi
github_username: htahmasbi
linkedin_username: hossein-tahmasbi-492372172

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.md
  - cv.md
  - contact.md

show_excerpts: true
